"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogModule = exports.Collections = exports.StandardLibrary = exports.NekoComponent = void 0;
var Neko_1 = require("./Neko");
Object.defineProperty(exports, "NekoComponent", { enumerable: true, get: function () { return Neko_1.NekoComponent; } });
var Standards_1 = require("./Standards");
Object.defineProperty(exports, "StandardLibrary", { enumerable: true, get: function () { return Standards_1.StandardLibrary; } });
var Collections_1 = require("./Collections");
Object.defineProperty(exports, "Collections", { enumerable: true, get: function () { return Collections_1.Collections; } });
var Log_1 = require("./Log");
Object.defineProperty(exports, "LogModule", { enumerable: true, get: function () { return Log_1.LogModule; } });
